version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: EventWebApp.WebAPI/Dockerfile
    ports:
      - "5112:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=eventdb;Username=postgres;Password=postgres
      - Jwt__Key=supersecretkey123456789
      - Jwt__Issuer=EventApp
      - Jwt__Audience=EventAppUsers
    depends_on:
      - postgres

  frontend:
    build:
      context: ./event-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
